spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    org:
      hibernate:
        envers:
          audit_table_suffix: _history
          revision_field_name: rev_id
          store_data_at_delete: true



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
    com.example.envers.controller: DEBUG
