spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
    com.example.envers.user.controller: DEBUG

org:
  hibernate:
    envers:
      store_data_at_delete: true
